version: "3.9"
services:
  dev:
    image: ${PROJECT}:${USER_UID}
    container_name: ${PROJECT}_${USER_UID}

    build:
      context: ../../context/
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: debian:bookworm-slim
        USERNAME: ${USER}
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        PYTHON_MAJOR_VERSION: 3
        PYTHON_MINOR_VERSION: 10
        PYTHON_PATCH_VERSION: 12
        POETRY_VERSION: "1.8.3"

    volumes:
      - type: bind
        source: ${HOME}/${WORKING_DIR}/${PROJECT}
        target: /home/${USER}/${PROJECT}
      - type: bind
        source: ${HOME}/.ssh
        target: /home/${USER}/.ssh
      - type: bind
        source: ${HOME}/.gitconfig
        target: /home/${USER}/.gitconfig

    # ports: 
    #   - '8888:8888'

    working_dir: /home/${USER}/${PROJECT}
    tty: true

    restart: always
    shm_size: '16gb'
    command: /bin/bash
    ulimits:
      memlock: -1
